### PR TITLE
Social Media web-application- Milestone 1

### PR DESCRIPTION
**Pull request by ahmetbozaci**
## Social Media web-application - Milestone 1

- Creating ERD for our Database and models
[ERD diagram](https://github.com/ahmetbozaci/ror-social-scaffold/blob/feature/analysis/docs/ER-Diagram.png)

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good introduction :+1:

To Improve :factory_worker:

- [x] You should have at least 5 tables in your ERD, `user` to store info about user, `comment` to store info about comments, `post` to store info about post, friendship table to store info if 2 users are friends or not and `like` to store all likes.
- [x] `User` table should have at least: ID, Name and Image-link columns.
- [x] `Post` table should have at least: ID, User_id and Content columns.
- [x] `Like` table should have at least: ID, Post_id and User_id columns.
- [x] `Comment` table should have at least: ID, User_id, Post_id and Content columns.
- [x] `Friendship` table should have at least; ID, User_id, Friend_id and Status columns.

- [x] Now, let's see together how your ERD should look:

```
1. One Friendship  is sent by only One User.
2. One User can send many Friendships.
3. One Friendship is received by only One User.
4. One User can receive many Friendships.
```

```
1. One User can create many Comments.
2. One Comment is created by only One User.
```

```
1. One User can create many Posts.
2. One Post is created by only One User.
```

```
1. One User can make many Likes.
2. One Like is made by only One User.
```

```
1. One Post can have many Likes.
2. One Like is just for One Post.
```

```
1. One Post can have many Comments.
2. One Comment is just for One Post.
```

Repo:

- [x] Please activate Github action even in this milestone because It allows you to automate your workflow by letting GitHub take care of a number of tasks which can be triggered by different of events on the platform.

- [x] It will be nice if you add a short description in your pull request in order to understand what you have done on this branch.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ahmetbozaci and @chrystalme  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, this milestone is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement the minimal requirements of this milestone, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The first thing is that you are missing the entity `like`, kindly add it
- [x] The table friend invitation should have `user_id` and `friend_id` fields
### Friendship and user table
- [x] Because a friend of a given user is coming from the same table users, then that relationship will be considered as a `many-to-many` relationship between table users and itself, in that case you will need what we call a junction table between table user and itself to help you implement a many-to-many relationship, that's why you need table `frienship` => this will be considered as that junction table. I highly recommend you to read [this article](https://support.airtable.com/hc/en-us/articles/218734758-Airtable-s-guide-to-many-to-many-relationships#manytomany) to learn more about the many to many relationship with junction table.

:point_right: After you understand well how to implement a many to many relationship, then change the association between friendship and user tables accordingly.

### user and likes
- [x] As a matter of fact, it's not one like which belongs to many users, I think you did the inverse. It should be `one user has many likes`, and `one like belongs to only one user`

### likes and post
- [x] The same thing applies to the association between likes and post, it's not one like which belongs to many post, it should be one post which has many likes 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @ahmetbozaci and @chrystalme :clap: :clap:
#### Good job so far :+1: However, some of the required changes mentioned in the last review are missing. Check my comments below :point_down:

#### 1) Likes & User:
 - The ERD should reflect the association: the `user has many likes `as opposed to the `likes has many users` which is your current ERD implementation

#### 2) Likes & Post:
 - The ERD should reflect the association: that `post has many likes `as opposed to the `likes has many posts` which is your current ERD implementation

#### _Reviewed by Temitayo Adeleke_

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey Happy Coders, 👋🏽 
 **Thank you for the good job you got going on.** We have one more final change to make.

## REQUIRED CHANGES

- [x] The association between the user and friendship tables should be as follows.
Screenshot_2021-03-16_15-32-48



**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.



### For more inquiries, mention me [@mke2111](https://github.com/mke2111) in this PR and I'll be glad to help.

### Ping me on slack for a  🆘  **Roy Mukuye**

**Comment by mimipeshy** [comment]
### STATUS: APPROVED 😁😀
Hello team @ahmetbozaci 👋great job on working on the requested changes. Your ERD is good to go. So i will mark this milestone as approved. You can go ahead and merge. All the best in the next milestones


Regards
Peris Ndanu

**Pull request closed without merging**
